### PR TITLE
Fixed tests

### PR DESCRIPTION
**Pull request by sebastienrouif**
Fixed module tests
Fixed application when using onlineWeatherAppModule
Upgraded to latest Koin version

### CODE REVIEW

**Comment by sebastienrouif** [comment]
it might be worth adding some documentation about 
```
koinApplication {
            ...
        }.checkModules {
            create<DetailViewModel> { parametersOf(viewModelId) }
        }
```
the way to add the parameters is quite nice but not that straightforward.
I'm happy to help

**Comment by arnaudgiuliani** [comment]
nice, thanks 👍 
Why adding the `fileProperties()` in the starters?

**Comment by sebastienrouif** [comment]
SERVER_UR is defined in koin.properties 
which is a property needed in remoteDataSourceModule

so I added `fileProperties()` in `MainApplication` so that any module combination can be used and I had to add in the test so that it passes when using `onlineWeatherApp` list of modules

**Comment by arnaudgiuliani** [comment]
oh yeah :)

**Pull request merged**
